version: '3.1'

services:
  flask_kafka_producer:
    build: .
    ports:
     - "5000:5000"
    volumes:
      - ./code/:/code/
    depends_on:
      - redis
  redis:
    image: "debian:jessie-slim"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.59
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
